#!/bin/bash
app="searx"

# causes the shell to exit if any subcommand or pipeline returns a non-zero status
set -e

# Source YNH helpers
. /usr/share/yunohost/helpers

# Retrieve arguments
domain=$(ynh_app_setting_get "$app" domain)
path=$(ynh_app_setting_get "$app" path)
is_public=$(ynh_app_setting_get "$app" is_public)

# Remove trailing slash to path
path=${path%/}
#force location to be / or /foo
location=${path:-/}

# Check domain/path availability
sudo yunohost app checkurl $domain$path -a $app
if [[ ! $? -eq 0 ]]; then
    echo "There is already an app on this URL : $domain$path" | sudo tee /dev/stderr
    exit 1
fi

final_path=/opt/yunohost/$app
if [ -d $final_path ]; then
    echo "There is already a directory: $final_path " | sudo tee /dev/stderr
    exit 1
fi

nginx_conf=/etc/nginx/conf.d/$domain.d/$app.conf
if [ -f $nginx_conf ]; then
    echo "There is already a nginx conf file at this path: $nginx_conf " | sudo tee /dev/stderr
    exit 1
fi

# Run install script
# sudo bash -c "./install $domain $path $is_public $app"

# Save specific settings
sudo yunohost app setting $app is_public -v $is_public

# Check depends installation
sudo apt-get install git build-essential libxslt-dev python-dev python-virtualenv virtualenv python-pybabel zlib1g-dev libffi-dev libssl-dev python-lxml uwsgi uwsgi-plugin-python -y

# Check Swap
if [ $(sudo swapon -s | wc -l) = 1 ];
then
    # It is NOT possible to setup a swap file on a tmpfs filesystem
    mount | grep /tmp | grep tmpfs > /dev/null 2>&1
    if [ $? = 1 ];
    then
        tmp_swap_file=/tmp/searx_swapfile
    else
        tmp_swap_file=/var/cache/searx_swapfile
    fi
    sudo dd if=/dev/zero of=$tmp_swap_file bs=1M count=256
    sudo chmod 600 $tmp_swap_file
    sudo mkswap $tmp_swap_file
    sudo swapon $tmp_swap_file
fi

# Restore sources
final_path=/opt/yunohost/$app
sudo cp -a "./sources" $final_path

# Init virtualenv
sudo virtualenv --system-site-packages $final_path
sudo bash -c "source $final_path/bin/activate && pip install -r $final_path/requirements-ynh.txt"

# Disable swapfile
if [[ -v "$tmp_swap_file" ]];
then
    sudo swapoff $tmp_swap_file
    sudo rm -f $tmp_swap_file
fi

#Configuration Searx
sudo cp "./conf/settings.yml" "$final_path/searx/settings.yml"

# Set permissions to searx directory
sudo useradd searx -d $final_path
sudo chown searx:searx -R $final_path

# Copy uwsgi config
sudo cp "./conf/searx.ini" "/etc/uwsgi/apps-available/$app.ini"
sudo ln -s "/etc/uwsgi/apps-available/$app.ini" /etc/uwsgi/apps-enabled/

# Nginx conf
sudo cp "conf/nginx.conf" $nginx_conf

if [ "$is_public" = "Yes" ];
then
    sudo yunohost app setting searx unprotected_uris -v "/"
fi

## Reload services
sudo service nginx reload
sudo service uwsgi restart
sudo yunohost service add uwsgi -l /var/log/uwsgi/app/$app.log

